version: '3'
services:
  adhearsion:
    #image: dwilkie/somleng:spec
    image: gbsomleng
    environment:
      - AHN_CORE_HTTP_ENABLE=false
      - AHN_CORE_HOST=freeswitch
      - AHN_CORE_PASSWORD=secret
      - AHN_CORE_USERNAME=adhearsion@localhost
      - AHN_ADHEARSION_DRB_PORT=9050
      - AHN_TWILIO_REST_API_ENABLED=1
      - "AHN_TWILIO_VOICE_REQUEST_METHOD=post"
      - "AHN_TWILIO_VOICE_REQUEST_URL=http://192.168.0.101:3000/api"
    depends_on:
      - freeswitch
  freeswitch:
    #image: dwilkie/freeswitch-rayo
    image: gbfree
    ports:
      - "5060:5060"
